[package]
name = "git-iblame"
version = "0.6.0-alpha"
edition = "2024"
authors = ["Koji Ishii <kojiishi@gmail.com>"]
description = "A command line tool to do `git blame` interactively."
keywords = ["git", "blame"]
repository = "https://github.com/kojiishi/git-iblame"
readme = "README.md"
license = "Apache-2.0"
exclude = [".github", ".gitignore"]

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
crossterm = { version = "0.29.0", features = ["osc52"] }
env_logger = "0.11.8"
git2 = { version = "0.20.2", default-features = false }
log = "0.4.27"

[dev-dependencies]
tempfile = "3.19.1"
