# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]
  check:
    - task: test
    - task: lint
    - task: fmt
  fix:
    - cargo clippy --fix {{.CLIPPY}}
    - task: fmt
  fmt:
    - cargo fmt {{.FMT}}
    - git diff
  lint: cargo clippy {{.CLIPPY}}
  test:
    cmds:
      - for: ['', '-Fgit2']
        cmd: cargo test {{.ITEM}} {{.TEST}}
    env:
      RUST_BACKTRACE: 1

vars:
  CLIPPY: '--all-targets --all-features -- -D warnings'
  FMT: '--all'
  TEST: ''
