#[derive(Clone, Debug, Hash, Eq, PartialEq)]
pub enum Command {
    PrevLine,
    NextLine,
    PrevPage,
    NextPage,
    FirstLine,
    LastLine,
    Older,
    Newer,
    LineNumber(usize),
    Search(String),
    SearchPrev,
    SearchNext,
    Copy,
    ShowCommit,
    ShowDiff,
    Repaint,
    Resize(u16, u16),
    Help,
    Quit,
    Timeout,
    Debug,
}
