name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Output rust version for educational purposes
        run: rustup --version

      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
